apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-workflow-pod-brain
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-workflow-pod-brain
spec:
  replicas: {{ .Values.texeraWorkflowPodBrain.numOfPods }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-workflow-pod-brain
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-workflow-pod-brain
    spec:
      serviceAccountName: {{ .Values.workflowPodBrain.name }}
      containers:
        - name: workflow-pod-brain
          image: {{ .Values.texeraWorkflowPodBrain.imageName }}
          ports:
            - containerPort: {{ .Values.texeraWorkflowPodBrain.service.port }}
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://{{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local:3306/{{ .Values.mysql.auth.database }}"
            - name: MYSQL_USER
              value: {{ .Values.mysql.auth.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.auth.password }}
{{/*            - name: MONGODB_URL*/}}
{{/*              value: "mongodb://{{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local:27017/{{ index .Values.mongodb.auth.databases 0 }}"*/}}