apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.workflowCompilingService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.workflowCompilingService.name }}
spec:
  replicas: {{ .Values.workflowCompilingService.numOfPods }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.workflowCompilingService.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.workflowCompilingService.name }}
    spec:
      containers:
        - name: {{ .Values.workflowCompilingService.name }}
          image: {{ .Values.workflowCompilingService.imageName }}
          ports:
            - containerPort: {{ .Values.workflowCompilingService.service.port }}
          env:
            - name: JDBC_URL
              value: "jdbc:mysql://{{ .Release.Name }}-mysql.{{ .Values.namespace }}.svc.cluster.local:3306/{{ .Values.mysql.auth.database }}"
            - name: JDBC_USERNAME
              value: {{ .Values.mysql.auth.username }}
            - name: JDBC_PASSWORD
              value: {{ .Values.mysql.auth.password }}
{{/*            - name: MONGODB_URL*/}}
{{/*              value: "mongodb://{{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local:27017/{{ index .Values.mongodb.auth.databases 0 }}"*/}}